version: "3.8"
services:
  grs-app:
    build: .
    container_name: "geoprocessamento-service"
    ports:
      - 5000:5000
  mongodb:
    image: mongo:7.0
    container_name: "mongodb"
    ports:
      - 27017:27017/tcp